pub(crate) use abolished_method_call::*;
pub(crate) use auth_method_outside_owner::*;
pub(crate) use company_field_outside_config::*;
pub(crate) use config_chainmap_patch::*;
pub(crate) use field_declaration::*;
pub(crate) use hand_rolled_range::*;
pub(crate) use http_exception_returned::*;
pub(crate) use http_json_string::*;
pub(crate) use n_plus_one_query::*;
pub(crate) use onchange_domain::*;
pub(crate) use orm_import::*;
pub(crate) use raise_unlink_override::*;
pub(crate) use receiver_fail_open::*;
pub(crate) use row_counter_in_test::*;

mod abolished_method_call;
mod auth_method_outside_owner;
mod company_field_outside_config;
mod config_chainmap_patch;
mod field_declaration;
mod hand_rolled_range;
mod http_exception_returned;
mod http_json_string;
mod n_plus_one_query;
mod onchange_domain;
mod orm_import;
mod raise_unlink_override;
mod receiver_fail_open;
mod row_counter_in_test;
